env = "local"

[local]
# setting
port = "CdMV_jqKWLiBHaJbgRPo4YfxR39z"
# api
api_auth = "NPbbZruJz3IuZ2fgNr70Tc6TnQmfzAdUzalhMyWd7Um3bsuLWKk="
api_customer = "sf75PBgitqs4AzLZjrm6RtCZjLXEd9CYeUELL99zXcjN19t-NpA="
api_transaction = "J15bDh6Ngp5BFNeLFpDcKWgy2IJk9uUwNTLHrlphwOSA6ctCdG0="
api_notif = "2qGSXF446dBkiCZErSXssPuZl99Uf6aEoFaMLBnbHqUxyKze8S4="

[development]

[production]