env = "local"

[local]
# setting
port = "Uv7EwYwc0XcIV6HY3xd0wFDXSTQm"
# database
mysql_host = "RbNBqHuGDnbFlImMtezyzvTyKD1guTkDr239AAjMqFrpXvA="
mysql_user = "lfPzSZkAcKyghc_9CHj_JkrWshI="
mysql_password = "qti8YwkOQncXLPy3rvZCQQ=="
mysql_database = "M_W_ZzhlTb8HjhX93KDrIphYxdM="
# elastic
elastic_host = "xywEwNOVSTaNOD6KXcsVhpPC83UAwtvljm8mlN3VysPInTjMcmt0o3ch"
elastic_indice_client = "Mk7rS3QkSL2oB_iQ_kdz5iei2LvSNzCXK0yD"
elastic_indice_user = "Qg_-c2Vipcbq9RIBARsjzIRhSEw9AI4TaQ=="
elastic_indice_token = "fcogI7RoKCcY_faO03TW6ZJvE3UiM5QNDr0="

[development]

[production]